baseURL = "https://www.danieljimenezm.com/"
languageCode = "en-us"
title = "Un Data Scientist Dice"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Daniel Jiménez M."
    email = "danieljimenez88m@gmail.com"
    year = 2020
    avatar = "images/daniel.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/fondo.png"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = false
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = true

[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 1
#[[menu.main]]
#    name = "blog"
#    url = "/post/"
#    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true



[[params.social]]
	title = "twitter"
	url = "https://twitter.com/DanielJimenezM9"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/djimenezm"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/carlosjimenez88M"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:danieljimenez88m@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
