---
title: "analyzing car fuel efficiency in R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries 

library(tidyverse)
library(statisticalModeling)
library(corrr)
library(moderndive)
library(broom)
theme_set(theme_classic())
```




## Load Datasets

```{r, warning=FALSE, message=FALSE}
big_epa_cars <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-15/big_epa_cars.csv") %>%
  mutate(uses_electricity = ifelse(highwayE > 0, "Uses Electricity", "Doesn't Use Electricity"))
```




# Some Abreviations and Definitions 

* MPG: Miles Per Galon
* Fuel Type 1 : Conventional Fuel
* Fuel Type 2 : Alternative Fuel (Electric , CNC, LPG)
* disp : Engine displacement in liters


```{r}
cor(big_epa_cars$city08, big_epa_cars$highway08,method = 'pearson')
```


```{r}
big_epa_cars%>%
  ggplot(aes(highway08,city08))+
  geom_point()+
  geom_abline(color='blue')+
  facet_wrap(~uses_electricity, scales = 'free')+
  expand_limits(x=0,y=0)+
  labs(x='Highway MPG',
       y='City MPG',
       title = 'How is fuel efficiency differ between city and Highway?')
```


```{r}
big_epa_cars%>%
  ggplot(aes(highway08,city08, col=factor(cylinders)))+
  geom_point()+
  geom_abline(color='blue')+
  facet_wrap(~uses_electricity, scales = 'free')+
  expand_limits(x=0,y=0)+
  labs(x='Highway MPG',
       y='City MPG',
       col='Cylinders',
       title = 'How is fuel efficiency differ between city and Highway?',
       subtitle = 'By Cylinders')
```





```{r}
big_epa_cars%>%
  filter(cityE==0)%>%
  mutate(VClass = fct_reorder(VClass,city08))%>%
  ggplot(aes(VClass,city08))+
  geom_boxplot(outlier.color = 'red')+
  coord_flip()+
  labs(title = 'Not Electric Cars ')
```



```{r}
big_epa_cars%>%
  filter(cityE==0)%>%
  ggplot(aes(displ,city08,group=cylinders))+
  geom_boxplot()
```




## Goal predict city fuel efficiency for non electric cars

```{r}
big_epa_cars%>%
  filter(cityE==0)%>%
  ggplot(aes(displ,city08))+
  geom_point()+
  expand_limits(x=0,y=0)
```

```{r}
# Cross Validation
non_electric_cars<-big_epa_cars%>%
  filter(cityA08==0, cityE==0)%>%
  sample_frac(1)

Training_set<-non_electric_cars%>%
  filter(row_number()%%5!=0)
  
```




```{r}
Training_set%>%
  ggplot(aes(displ,city08))+
  geom_point()+
  geom_smooth(method = 'lm')
```




```{r}
library(splines)
augment_data<-lm(city08~ns(displ,2),data = Training_set)%>%
  augment(data=Training_set)

```




```{r}
augment_data%>%
  ggplot(aes(displ,city08))+
  geom_line(aes(y=.fitted),color='red', size=2)+
  geom_point()
```



```{r}
models <- tibble(df = 1:10) %>%
  mutate(lm_model = map(df, ~ lm(city08 ~ ns(displ, df = .), data = Training_set)))
augmented_unnested <- models %>%
  mutate(augmented = map(lm_model, augment, data = Training_set)) %>%
  unnest(augmented)
augmented_unnested %>%
  ggplot(aes(displ, city08)) +
  geom_point(data = Training_set) +
  geom_line(aes(y = .fitted, color = factor(df)), size = 2) +
  labs(x = "Engine volume (L)",
       y = "City MPG",
       color = "# of degrees of freedom") +
  expand_limits(x = 0, y = 0)
```




```{r}
glanced_models <- models %>%
  rename(spline_df = df) %>%
  mutate(glanced = map(lm_model, glance, data = training_set)) %>%
  unnest(glanced)
glanced_models %>%
  ggplot(aes(spline_df, adj.r.squared)) +
  geom_line()
```




```{r}
lm(city08 ~ ns(displ, 4), data = Training_set) %>%
  anova() %>%
  tidy() %>%
  mutate(pct_variation = sumsq / sum(sumsq))
```


```{r}
Training_set%>%
  ggplot(aes(year,city08))+
  geom_point()+
  geom_smooth(method = 'loess')
  
```


```{r}
Training_set%>%
  mutate(VClass=fct_lump(VClass,10))%>%
  group_by(year,VClass)%>%
  summarize(avg_efficiency=mean(city08))%>%
  ggplot(aes(year,avg_efficiency,color=VClass))+
  geom_line()+
  expand_limits(y=0)
```



```{r}
efficiency_time <- Training_set %>%
  mutate(VClass = fct_lump(VClass, 6),
         guzzler = !is.na(guzzler)) %>%
  group_by(year = 2 * floor(year / 2), VClass) %>%
  summarize_at(vars(city08, cylinders, displ, guzzler), mean)

```

```{r}
efficiency_time %>%
  ggplot(aes(year, city08, color = VClass)) +
  geom_line() +
  expand_limits(y = 0)

```

```{r}
efficiency_time %>%
  ggplot(aes(year, displ, color = VClass)) +
  geom_line() +
  expand_limits(y = 0)
```



```{r}
efficiency_time %>%
  ggplot(aes(year, guzzler, color = VClass)) +
  geom_line() +
  expand_limits(y = 0)

```

