---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---


```{r}
library(tidyverse)
library(tidymodels)
library(moderndive)
library(lubridate)
library(mrgsolve)
library(tidytable)
library(stringr)
library(tidytext)
library(janeaustenr)
library(tidyr)
library(tm)
```


## import database






```{r}
gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv')
gdpr_text <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_text.tsv')
```




```{r}
gdpr_violations%>%View()
```

```{r}
gdpr_text%>%View()
```


## Explore Data



```{r}
library(tidytext)
gdpr_violations%>%
  mutate(date=mdy(date))%>%
  mutate(year=year(date))%>%
  filter(year>=2019)%>%
  group_by(year,name,controller)%>%
  summarize(total=n())%>%
  ungroup()%>%
  group_by(year,name)%>%
  summarize(total=sum(total))%>%
  mutate(year=as.factor(year),
         name=reorder_within(name,total,year))%>%
  ggplot(aes(name,total, fill=name))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~year,scales = "free_y")+
  scale_x_reordered() +
  scale_y_continuous(expand = c(0,0))+ 
  coord_flip()
  
```


```{r}
top_controller<-gdpr_violations%>%
  mutate(date=mdy(date))%>%
  mutate(year=year(date))%>%
  filter(year!=1970)%>%
  group_by(year,name)%>%
  count(controller,sort = TRUE)%>%
  ungroup()


top_controller%>%
  filter(year>=2019)%>%
  filter(!str_detect(controller,"pdf"))%>%
  group_by(controller)%>%
  top_n(10)%>%
  ungroup()%>%
  mutate(year=factor(year),
         name=reorder_within(name,n,year)
         )%>%
  ggplot(aes(name,n,fill=controller))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~year,scales="free_y")+
  scale_x_reordered() +
  scale_y_continuous(expand = c(0,0))+
  theme(legend.position="bottom")+
  coord_flip()
```




```{r}
gdpr_violations%>%
  mutate(date=mdy(date))%>%
  mutate(year=year(date))->gdpr_violations

gdpr_violations%>%
  filter(year>=2019)%>%
  group_by(year,name,article_violated)%>%
  summarize(total=n())%>%
  ungroup()
regexp <- "[[:digit:]]+"
gdpr_violations%>%
  filter(year>=2019)%>%
  separate(article_violated,into = c("art","art1"),sep = "\\|")%>%
  mutate(art_principal=as.numeric(str_extract(art,regexp)))%>%
  select(c(id,art_principal))->article

```




```{r}
gdpr_violations%>%
  filter(year>=2019)%>%
  separate(article_violated,into = c("art","art1"),sep = "\\|")%>%
  mutate(art_principal=as.numeric(str_extract(art,regexp)))%>%
  select(-c(art1,art))->violations



```





```{r}
library(tm)
library(topicmodels)

gdpr_text%>%
  group_by(chapter)%>%
  count(sort = TRUE)

article<-gdpr_text%>%
  select(article,gdpr_text)%>%
  distinct(article,.keep_all = TRUE)
  
text_df<-article%>%
  tibble(line=1:99,text=gdpr_text)%>%
  select(c(line,text))

data("stop_words")
tidy_art<-text_df%>%
  unnest_tokens(word,text)%>%
  anti_join(stop_words)

tidy_art %>%
  count(word, sort = TRUE)


article_bigram<-text_df%>%
  unnest_tokens(bigram,text,token = "ngrams",n=7)

article_bigram%>%
  count(bigram,sort=TRUE)




grams_separated <- article_bigram %>%
  separate(bigram, c("word1", "word2","word3","word4","word5","word6","word7"), sep = " ")


grams_filtered<-grams_separated%>%
  filter(!word1 %in% stop_words)%>%
  filter(!word2 %in% stop_words)%>%
  filter(!word3 %in% stop_words)%>%
  filter(!word4 %in% stop_words)%>%
  filter(!word5 %in% stop_words)%>%
  filter(!word6 %in% stop_words)%>%
  filter(!word7 %in% stop_words)

```





```{r}
grams_counts<-grams_filtered%>%
  count(word1,word2,word3,word4,word5,word6,word7, sort = TRUE)

grams_united<-grams_filtered%>%
  unite(bigram,word1,word2,word3,word4,word5,word6,word7,sep =" ")

grams_united
```



```{r}
grams_tf_idf <- grams_united %>%
  count(line, bigram) %>%
  bind_tf_idf(bigram, line, n) %>%
  arrange(desc(tf_idf))

grams_tf_idf
```



```{r}
library(igraph)
# filter for only relatively common combinations
gram_graph <- grams_counts %>%
  graph_from_data_frame()

gram_graph
```




```{r}
library(ggraph)
ggraph(gram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```



```{r}

article_dtm<-text_df%>%
  unnest_tokens(word,text)%>%
  count(line,word)%>%
  cast_dtm(line,word,n)

article_dtm
```


```{r}
# set a seed so that the output of the model is predictable
ap_lda <- LDA(article_dtm, k = 2, control = list(seed = 1234))
ap_lda

ap_topic<-tidy(ap_lda,matrix="beta")
ap_topic
```


```{r}
ap_top_terms <- ap_topic %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

ap_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  scale_x_reordered()
```


```{r}
beta_spread <- ap_topic %>%
  mutate(topic = paste0("topic", topic)) %>%
  spread(topic, beta) %>%
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))

beta_spread
```



```{r}
ap_documents <- tidy(ap_lda, matrix = "gamma")
ap_documents
```












