---
title: "Ipad Pro para Machine Learning"
date: 2020-11-15
output: html_document
mathjax: "true"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ipad Pro para Machine Learning

Este es un post un poco diferente a los que normalmente acostumbro a escribir, pero la razón por la cual lo hago no es menos valedera a un tema de aplicación conceptual de estadística o machine learning. Sin ganas de entrar a una discusión tipo fanboy de una marca, hablo desde la experiencia de uso y desarrollo del iPad Pro como herramienta de trabajo como Data Scientist.

Unas de las razones por la cual empecé a usarla (la idea original) era aprovechar que el dispositivo tenia unas ventajas en GPU y procesamiento gráfico el cual poden ayudarme a la hora de entrenar modelos o hacer algo de ingeniera de datos, pero resulta que poco a poco fui aprendiendo a trabajar en cosas más profundas e interesantes que estas.

Por lo tanto expondré algunas ideas de como generar un `workflow` del iPad para el trabajo de ciencia de datos.

### Manejor y edición de repositorios

Como es costumbre la mayoría de científicos de datos trabajamos en Github, dado que tenemos proyectos colaborativos, por lo tanto a la hora de hacer un `merge` o anexar cambios en una parte del código es necesario poder clonar el repo y hacerle las ediciones, para ello contamos con [Working Copy](https://workingcopyapp.com/).


Esta app nos permite, clonar, modificar, comentar, mergear y demás acciones nativas de un repo de Github, más una buena practica es editar los códigos o lo que estemos trabajando con un editor tipo `Visual Studio Code` y para ello contamos con [Kodex](https://kodex.app/), el cual tiene un nivel de eficiencia bastante bueno!


Paso seguido si queremos trabajar de manera detallada los códigos , o en forma los modelos de analítica y Machine Learning podemos usar alguna de las siguientes opciones :

* [Juno](https://juno.sh/junoconnect/): Es el Interfaz tipo Jupyter Notebook para Ipad.
* [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb): Cuadernos en google que nos permiten desarrollar el trabajo completo en las libretas de Jupyter. (Recuerden que acá se puede trabajar tanto R como Python)

## Conexiones a máquinas

Gracias a [blink](https://blink.sh/docs/basics/navigation) se pueden generar conexiones tipo SSH desde el iPad hacia servidores u host, es algo difícil de manejar al principio dado que es necesario  manejar `terminal` o `cmd` para poder crear las conexiones.

Paso seguido, si se integra blink con Juno se puede el workflow para la etapa de producción de código queda completa y la verdad el tiempo de desarrollo es super rápido.

## SQL

Para finalizar quiero contarles que una gran parte del trabajo que desarrollamos como científicos de datos esta enfocado en el proceso de ETL y en algunas ocaciones es necesario trabajar con [SQL](https://apps.apple.com/es/app/sql-server-mssql-by-sqlpro/id1176218536) y en el iPad esta la opción de trabajar con [sqlpro](https://apps.apple.com/es/app/sql-server-mssql-by-sqlpro/id1176218536), más si el trabajo que usted realiza esta atado a una necesidad mayor de procesamiento (map-reduce) le recomiendo usar BigQuery desde la aplicación móvil de Google.

Un dato especial: Si quieren trabajar ya en cosas de deep Learning pueden basarse en RaspberryPi, lo cual les permitirá trabajar entrenamientos largos y con alta cantidad de arquitecturas y capas como sean necesarias.

Y eso es todo por esta entrada espero que les guste!!!













