---
title: "iPad Y Machine Learning"
date: 2020-11-15
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Este es un post un poco diferente a los que normalmente acostumbro a escribir, pero la razón por la cual lo hago no es menos valedera a un tema de aplicación conceptual de estadística o machine learning. Sin ganas de entrar a una discusión tipo fanboy de una marca, hablo desde la experiencia de uso y desarrollo del iPad Pro como herramienta de trabajo como Data Scientist.

Unas de las razones por la cual empecé a usarla (la idea original) era aprovechar que el dispositivo tenia unas ventajas en GPU y procesamiento gráfico el cual poden ayudarme a la hora de entrenar modelos o hacer algo de ingeniera de datos, pero resulta que poco a poco fui aprendiendo a trabajar en cosas más profundas e interesantes que estas.

Por lo tanto expondré algunas ideas de como generar un `workflow` del iPad para el trabajo de ciencia de datos.

### Manejor y edición de repositorios

Como es costumbre la mayoría de científicos de datos trabajamos en Github, dado que tenemos proyectos colaborativos, por lo tanto a la hora de hacer un `merge` o anexar cambios en una parte del código es necesario poder clonar el repo y hacerle las ediciones, para ello contamos con [Working Copy](https://workingcopyapp.com/).

